config/routes.rb
Rails.application.routes.draw do  
  resources :trainings
  
  resources :partners, only: [:new, :create, :destroy]
  
  resources :places do
    resources :trainings
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registration: 'user/registrations' }
  
  resources :users do
    collection do
       get 'dashboard'
    end 
    resources :trainings
  end

  root 'home#index'
end

app/models/training.rb
class Training < ApplicationRecord
  #searchkick word_start: [:sport]

  belongs_to :user
  belongs_to :place

  has_many :rateds
  #has_many :users, through: :rateds
  has_many :partners

  has_many_attached :images

  enum sport: [:Running, :Trekking, :Roller, :Bike, :Climbing, :Surf, :Funcional, :Tenis, :Futbol, :Voleibol, :Slackline, :Birdwatching]
  enum level: [:Básico, :Intermedia, :Avanzada]

  #validates :date_cannot_be_in_the_past
  audited only: :rating, on: [:update, :destroy]
  after_update :average_stars

  # def date_cannot_be_in_the_past
  #   if date.present? && date < Date.today
  #     errors.add(:date, "must be from today on")
  #   end
  # end 

  def to_s
    self.sport
  end

  #Pides solicitud de entrenamiento (partner)
  
  def suggest_partners
      current_partners_id = self.partners.map{|f| f.partner_id}
      current_partners_id.push(self.id)
      @suggest = User.where.not(id: current_partners_id)
  end

  def partner_list
    users = self.partners.map{|f| f.partner_id}
    users.push(self.id)
    return users
  end

  def follow?(user)
    return (partners.where('partner_id=?', user).count == 1)
  end

  # Si el entrenamiento terminó, puedes evaluar
  def concluded?
     self.date < Date.today
  end

  #Entregar evaluacion

  def average_stars
    n = self.revisions.pluck(:rating)
    x = self.audits.all.count
    if x > 0 && !n.empty?
      n.sum/x
    else
      0
    end
  end
  
  # Si fue evaluado, no evaluarlo de nuevo
  def rated?(user)
    !!self.rateds.find{|rate| rate.user_id == user.id}
  end

  # Kaminari
  paginates_per 15
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :set_training, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user! 
  before_action :set_sports, :set_levels, :set_places, only: %i[new edit]  
  
  # GET /trainings or /trainings.json
  def index
    @training_group = Training.group(:user_id).count.transform_keys {|key| User.find(key).name}
    @training_sport = Training.group(:sport).count

    @trainings = Training.with_attached_images.all.order('date ASC').page(params[:page])
    @training = Training.new
  end

  # GET /trainings/1 or /trainings/1.json
  def show
    @training = Training.find(params[:id])
    @place = Place.new
  end

  # GET /trainings/new
  def new
    @training = current_user.trainings.build 
    @trainings = Training.all
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings or /trainings.json
  def create
    @training = Training.new(training_params.merge(user: current_user)) #, place: :place_id
    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: "Training was successfully created." }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1 or /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: "Training was successfully updated." }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1 or /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: "Training was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def partners #pendiente para historia DUS003
  #   @partner = @user.partner.create(user_id: current_user.id, partner_id: @training.user.id)
  #   redirect_to root_path, notice: "Quiero entrenar contigo!"
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    def set_sports
      @sports = Training.sports.map { |sport, id| [sport, sport] }
    end

    def set_levels
      @levels = Training.levels.map { |level, id| [level, level] }
    end

    def set_places
      @places = Place.pluck :location, :id
    end
    
    def set_current_training
      @training = training.find(params[:training_id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:name, :date, :sport, :level, :active, :place_id, :rating, images: []) #:user_id, :place_id)
    end
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: @training, local: false) do |form| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(training.errors.count, "error") %> prohibited this training from being saved:</h2>

      <ul>
        <% @training.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row px-3 pb-3">
    <h6 class="px-0 mb-1"><%= form.label :name %></h6>
    <%= form.text_field :name, class:"custom-input" %>
  </div>

  <div class="row px-3 pb-3">
    <h6 class="px-0 mb-1"><%= form.label :date %></h6>
    <div class="ps-0 custom-select"><%= form.datetime_select :date %></div>
  </div>

  <div class="row px-3 pb-3">
    <div class="col-12 col-md-6">
      <div class="row me-3 custom-select">
        <h6 class="px-0 mb-1"><%= form.label :sport %></h6>
        <%= form.select :sport, @sports, prompt: "Seleccione una opción"%> 
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="row row me-3 custom-select">
        <h6 class="px-0 mb-1"><%= form.label :level %></h6>
        <%= form.select :level, @levels, prompt: "Seleccione una opción"%> 
      </div>
    </div>
  </div>

  <div class="row px-3 pb-3">
    <div class="col-12 col-md-6">
      <div class="row row me-3 custom-select">
        <h6 class="px-0 mb-1"><%= form.label :place_id %></h6>
        <%= form.select :place_id, @places, prompt: "Seleccione una opción" %> 
      </div>
    </div>
    <div class="col-12 col-md-6">
      <div class="row row me-3"> <!--active storage, preguntar-->
        <h6 class="px-0 mb-1"><%= form.label :image %></h6>
        <%= form.file_field :images, multiple: true %>
      </div>
    </div>
  </div>

  <%#<p><%= link_to 'Add new place', new_place_path, remote: true %></p>

  <%# <div class="field"> <!--Render de ujs de places, para que con un boton se genere un formulario de ubicación nueva.-->
    <%= form.label :place_id %>
  <%# <%= form.select :place_id, @places, prompt: "Seleccione una opción" %>
  <%# </div> %>

  <div class="text-center">
    <%= form.submit data: { disable_with: 'Creando tu entrenamiento!' }, class: "custom-button" %>
  </div>
<% end %>

app/views/trainings/_training.html.erb
<tr data-id="<%= training.id %>">
    <%= render 'training_detail', post: post %>
</tr>

app/views/trainings/_training_detail.html.erb
<div class="card h-100">
          <% if training.images.any? %>
          <%= image_tag training.images.first.variant(resize: "100x100").processed %> <!--Chequear!!-->
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= training.name %></h5>
          </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><i class="fas fa-street-view"></i> <%= training.place.location %></li>
              <li class="list-group-item"><i class="fas fa-running"></i> <%= training.sport %></li>
              <li class="list-group-item"><i class="fas fa-signal"></i> <%= training.level %></li>
              <li class="list-group-item"><i class="far fa-calendar-alt"></i> <%= training.date.strftime('%d-%m-%y -> %H:%M') %></li>
            </ul>
          <div class="card-body">
            <!--Rated-->
            <% if user_signed_in?%>
              <td id='td-style'><% if training.concluded? %>
                <td><%=link_to 'Calificar', training %></td>
                  <% if training.rated?(current_user)%> 
                    <td><%= link_to 'Calificar', training_rateds_path(training) %></td>
                  <% end %>
              <% else %>
                  <%= '' %>
              <% end %></td>
            <% end %>
            <a href="#" class="card-link">
              <%= link_to 'Mirar', training %>
              <% if user_signed_in? && @training.user == current_user %>
                <%= link_to 'Editar', edit_training_path(@training) %> |
              <% end %>   
            </a>
            <a href="#" class="card-link">
              <%= link_to 'Quiero Entrenar', training %> <!--Este link es para pedir solicitud de entrenamiento--> 
            </a>
          </div>
        </div>

app/views/trainings/create.js.erb
var div = document.querySelector("div#training");
console.log(div)
var new_tr = document.createElement("#ul");
new_tr.dataset.id = <%= @training.id %>
var training_content = '<%= j render "training_detail", training: @training %>'

new_tr.innerHTML = training_content
table.appendChild(new_tr)


var input_text = document.querySelector('[name="training[name]"]')
input_text.value = ''

var input_text = document.querySelector('[name="training[sport]"]')
input_text.value = ''

var input_text = document.querySelector('[name="training[level]"]')
input_text.value = ''

var input_text = document.querySelector('[name="training[date]"]')
input_text.value = ''

var input_text = document.querySelector('[name="training[user.name]"]')
input_text.value = ''

var input_text = document.querySelector('[name="training[place_id]"]')
input_text.value = ''

app/views/trainings/destroy.js.erb
var tr = document.querySelector('tr[data-id="<%= @training.id %>"]')
tr.innerHTML = ''

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form', training: @training %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/edit.js.erb
var training_detail = document.querySelector('#training_detail')
training_detail.innerHTML = '<%= j render "form", training: @training %>'

app/views/trainings/index.html.erb
<h1 class="training">Entrenamientos</h1>
 
  <div class="col-xs-4 col-sm-2 col-md-2 right"> 
    <% if user_signed_in? == current_user %>
      <%= link_to 'New Training', new_training_path, class: "btn btn-info btn-sm rigth" %>  
    <% end %>  
  </div>

  <div id="trainings" class="row row-cols-1 row-cols-md-3 g-5 m-5" style="margin-top:20px">
    <% @trainings.reverse.each do |training| %> <!--reverse.each: da vuelta el orden... a,b,c sería c,b,a-->

      <div id="tr" class="col custom-shadow card-training" >
        <div class="card h-100 ">
          <% if training.images.any? %>
            <%= image_tag training.images.first.variant(resize: "535x535").processed %> <!--Chequear!!-->
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= training.name %></h5>
          </div>
            <ul class="list-group list-group-flush card-body">
              <li class="list-group-item"><i class="icon ion-md-contact"></i> <%= training.user.name%></li>
              <li class="list-group-item"><i class="fas fa-running"></i> <%= training.sport %></li>
              <li class="list-group-item"><i class="fas fa-signal"></i> <%= training.level %></li>
              <li class="list-group-item"><i class="fas fa-street-view"></i> <%= training.place.location %></li>
              <li class="list-group-item"><i class="far fa-calendar-alt"></i> <%= training.date.strftime('%d-%m-%y / %H:%M') %></li>
            </ul>
          <div class="card-body">
            <!--Rated-->
            <% if user_signed_in?%>
              <a href="#" class="card-link">
                <%= link_to 'Mirar', training %>
                 <!--Este link es para pedir solicitud de entrenamiento--> 
                <tbody class="text-center">
                    <% if user_signed_in? && training.concluded? %>
                         <%# <% if current_user.partners.pluck(:partner_id).include?(training.user.id) && user.id == training.user.id %>  
                        <%= link_to 'Entrenar', users_path(@user) %> <!--que vaya al dashboard del usuario dueño del entrenamiento-->      
                    <% end %>
                </tbody>
              </a>
              <td id='td-style'>
                <% if training.concluded? %>
                  <td><%=link_to 'Calificar', training %></td>
                <% end %></td>
                
                <%= training.average_stars.times do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                      <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    </svg>
                <% end %><br><br>
              
              <% if @training.user == current_user %>
                <a href="#" class="card-link">
                  <%= link_to 'Editar', edit_training_path(@training) %> |
                </a>
              <% end %> 
            <% end %>    
          </div>
        </div>
      </div>
    <% end %>  
  </div>

  <!--Paginación-->
  <section class="my-1">
    <div class="d-flex justify-content-end my-2">
      <%= link_to_previous_page @trainings, '<<', class: "text-decoration-none text-light btn btn-info btn-lg" %>
      <%= link_to_next_page @trainings, '>>', class: "text-decoration-none btn btn-info btn-lg text-light" %>
    </div>
  </section>

<%# 
<div style="width: 500px">
  <%= pie_chart @training_sport, legend: "bottom" %>
  <%# <%= line_chart @training_group, legend: ""%> 
<%# </div> %>

app/views/trainings/new.html.erb
<h1>Nuevo Entrenamiento</h1>

<div class="row">
    <div class="col-md-8 mb-3">
        <div class="card">
            <div class="card-header">
                <h3 class="mb-0">Nuevo Entrenamiento</h3>
            </div>
            <div class="card-body">
                <%= render "form" %>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h3 class="mb-0">No está tu lugar! Agrégalo!</h3>
            </div>        
            <div class="card-body fields">
                <%= link_to "Lugar", new_place_path %>
            </div>
        </div>
    </div>    
<div>

app/views/trainings/show.html.erb
<div class="row p-5 mt-5">
  <!--izq-->
  <div class="col-6 col-md-6  ">
    <div class="card mb-3 mx-auto custom-shadow" style="max-width: 540px;">
      <div class="row g-0">
        <div class=" img col-12">
        <% if @training.images.any? %>
          <% @training.images.each do |image| %>
          <%= image_tag image.variant(resize: "535x535").processed %>
          <% end %>
        <% end %>
        </div>
        <div class="col-12">
          <div class="card-body">
            <h5 class="card-title"><%= @training.name %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item p-3"><i class="icon ion-md-contact lead"></i> <%= @training.user.name%></li>
            <li class="list-group-item p-3"><i class="fas fa-running lead"></i> <%= @training.sport %></li>
            <li class="list-group-item p-3"><i class="fas fa-signal lead"></i> <%= @training.level %></li>
            <li class="list-group-item p-3"><i class="fas fa-street-view lead"></i> <%= @training.place.location %></li>
              <li class="list-group-item"><i class="far fa-calendar-alt"></i> <%= @training.date.strftime('%d-%m-%y / %H:%M') %></li>
          </ul>
          <hr>
          <div>
          <!--Evaluar-->
            <div class="m-3">
              <% if @training.concluded? && @user != current_user %> 
                <%= form_with(model: @training) do |form| %>
                  <div class="field">
                    <%= form.label :rate_from_1_to_5 %>
                    <%= form.select(:rating, options_for_select([[1, 1],[2, 2],[3, 3],[4, 4],[5, 5]])) %>
                  </div>
                  <div class="actions">
                    <%= form.submit "Evalúa"%>
                  </div>
                <% end %>
              <% else %>
                <div id="error_explanation">
                  <h2><%= pluralize(@training.errors.count, "error") %> No puedes evaluar:</h2>
                  <ul>
                    <% @training.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>              
              <% end %>
              <br>
                <%= @training.average_stars.times do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                  </svg>
                <% end %>
            </div>
            
          </div>
          <div class="card-body">
            <a href="#" class="card-link">
              <% if user_signed_in? && @training.user == current_user %>
                <%= link_to 'Edit', edit_training_path(@training) %> |
              <% end %>   
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
    
  <!--der-->

  <div class="col-12 col-md-6">
    <p>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=700x700&center=#{@place.latitude},#{@place.longitude}&key=AIzaSyDKo32oRZX1c3LtHxc0hXodf24IXpFRtbo", alt: "Map" %> 
    </p>  
  </div>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.js.erb
var training_detail = document.querySelector('#training_detail')

training_detail.innerHTML = '<p><strong>Nombre:</strong><%= @training.name %></p>'
training_detail.innerHTML += '<p><strong>Deporte:</strong><%= @training.sport %></p>'
training_detail.innerHTML += '<p><strong>Nivel:</strong><%= @training.level %></p>'
training_detail.innerHTML += '<p><strong>Fecha:</strong><%= @training.date %></p>'
training_detail.innerHTML += '<p><strong>Deportista:</strong><%= @training.user.name %></p>'
training_detail.innerHTML += '<p><strong>Lugar:</strong><%= @training.place.id %></p>'

var input_text = document.querySelector('[a="training[Show]"]')
input_text.value = ''

app/views/trainings/update.js.erb
var tr = document.querySelector('tr[data-id="<%= @training.id %>"]')
tr.innerHTML = '<%= j render "training_detail", training: @training %>'

var training_detail = document.querySelector('#training_detail')
training_detail.innerHTML = ''