config/routes.rb
Rails.application.routes.draw do  
  resources :trainings
  
  resources :partners, only: [:new, :create, :destroy]
  
  resources :places do
    resources :trainings
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registration: 'user/registrations' }
  
  resources :users do
    collection do
       get 'dashboard'
    end 
    resources :trainings
  end

  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trainings
  
  # has_many :partners
  # has_many :friends, -> { where partners: { state: :accepted }}, through: :partners
  # has_many :requested_friends, -> { where partners: { state: :requested }}, through: :partners, source: :friend
  # has_many :pending_friends, -> { where partners: { state: :pending }}, through: :partners, source: :friend
  # has_many :blocked_friends, -> { where partners: { state: :blocked }}, through: :partners, source: :friend


  
  def to_s
    self.name 
  end


  def has_partner?(friend)
    return true if self == friend
    partners.map(&:friend_id).include?(friend.id)
  end

  # def requested_friends_with?(friend)
  #   return false if self == friend
  #   requested_friends.map(&:id).include?(friend.id)
  # end
  
  def pending_friends_with?(friend)
    return false if self == friend
    pending_friends.map(&:id).include?(friend.id)
  end
  
  def friends_with?(friend)
    return false if self == friend
    friends.map(&:id).include?(friend.id)
  end
    
  def friend_request(friend)
    unless self == friend || Partner.where(user: self, friend: friend).exists?
      transaction do
        Partner.create(user: self, friend: friend, state: :pending)
        Partner.create(user: friend, friend: self, state: :requested)
      end
    end
  end

  def accept_request(friend)
    transaction do
      Partner.find_by(user: self, friend: friend, state: [:requested])&.accepted!
      Partner.find_by(user: friend, friend: self, state: [:pending])&.accepted!
    end
  end

  def reject_request(friend)
    transaction do
      Partner.find_by(user: self, friend: friend)&.destroy!
      Partner.find_by(user: friend, friend: self)&.destroy!
    end
  end
  
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  GET /resource/sign_in
  def new
    super
  end

  POST /resource/sign_in
  def create
    super
  end

  DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = current_user.trainings.all
    @user = User.new

    @user_pie = current_user.trainings.group(:sport).count
    @user_line = current_user.trainings.group(:name).count

  end
  
  # GET /users/1 or /users/1.json
  def show
    @user_sport = current_user.trainings.group(:sport).count
    @user_group = current_user.trainings.group(:name).count.transform_keys {|key| User.find(key).name } #ojo

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :image)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: false) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.js.erb
var table = document.querySelector('table#users tbody')
var new_tr = document.createElement('tr')
new_tr.dataset.id = <%= @user.id %>
var user_content = '<%= j render "user_detail", user: @user %>'

new_tr.innerHTML = user_content
table.appendChild(new_tr)


var input_title = document.querySelector('[name="user[name]"]')
input_title.value = ''

var input_content = document.querySelector('[name="user[image]"]')
input_content.value = ''

app/views/users/dashboard.html.erb
<p id="notice"><%= notice %></p>

<h1>Mi Perfil</h1>


<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Social Media</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.profile.social_media%> </td>
        <td><%= user.profile.image%> </td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= pie_chart @user_group, legend: "bottom" %>
<%#= link_to 'New Profile', new_user_profile_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
  <div class="d-flex" id="">
    <!-- Sidebar -->
    <div id="sidebar-container" class="bg-primary">
      <div class="logo">
        <h4 class="text-light font-weight-bold mb-0">Partner</h4>
      </div>
      <div class="menu">
        <ul class="list-group list-group-flush">
          <li class="d-block text-light p-3 border-0"><i class="icon ion-md-people lead mr-2"></i>  <%= current_user.name %></li>
          <li class="d-block text-light p-3 border-0"><i class="icon ion-md-stats lead mr-2"></i>  <%= current_user.email %></li>
          <li class="d-block text-light p-3 border-0"><i class="icon ion-md-apps lead mr-2"></i>  <%= link_to 'Nuevo entrenamiento', new_training_path, class: "d-block text-light p-3 border-0" %></li>
          <%# <li class="d-block text-light p-3 border-0"><i class="icon ion-md-person lead mr-2"></i> <%= current_user.total_partners </li>%>
          <li class="d-block text-light p-3 border-0"><i class="icon ion-md-settings lead mr-2"></i>  <%= link_to 'Edita tu perfil', edit_user_registration_path, class: "d-block text-light p-3 border-0"  %></li>
        </ul>
          <%= pie_chart @user_pie, legend: "bottom"%>
          <%= line_chart @user_line, legend: "bottom"%>
      </div>
    </div>

    <!-- Page Content -->
    <div id="content" class="w-100">

      <section class="py-3">
        <div class="container">
          <div class="row">
            <div class="col-lg-9 col-md-8">
              <h1 class="font-weight-bold mb-0">Bienvenido <%= current_user.name %></h1>
              <p class="lead text-muted">Revisa la última información</p>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-3 col-md-6 d-flex stat my-3">
                  <div class="mx-auto">
                    <h6 class="text-muted">Has creado <%= current_user.trainings.count %> entrenamientos!</h6>
                    <h3 class="font-weight-bold">
                      <% if current_user.trainings.count >= 6 %>
                        <p> Eres un gran Atleta!</p>
                      <% else %>
                        <p> Puedes crear más!</p>
                      <% end %></h3>
                  </div>
                </div>
              </div>
            </div>
          
            <!--Entrenamientos realizados -->
            <div id="trainings" class=" card-body row row-cols-1 row-cols-md-3 g-4">
              <% current_user.trainings.reverse.each do |training| %>
                <div id="tr" class="col">
                  <div class="img card h-100">
                    <% if training.images.any? %>
                      <%= image_tag training.images.first.variant(resize: "500x500").processed %> <!--Chequear!!-->
                    <% end %>
                    <div class="card-body">
                      <h5 class="card-title"><%= training.name %></h5>
                      <ul class="list-group list-group-flush">
                        <li class="list-group-item"><i class="fas fa-street-view"></i> <%= training.place.location %></li>
                        <li class="list-group-item"><i class="fas fa-running"></i> <%= training.sport %></li>
                        <li class="list-group-item"><i class="fas fa-signal"></i> <%= training.level %></li>
                        <li class="list-group-item"><i class="far fa-calendar-alt"></i> <%= training.date.strftime('%d-%m-%y -> %H:%M') %></li>
                      </ul>   
                    </div>
                  </div>
                </div>
              <% end %> 
            </div>
            <!--Partners-->
            <div class="container p-2">
              <div class="row">
                <div class="col-12">  
                  <div class="col-12 border border-secondary rounded">
                    <ul class="list-group p-2">
                      <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-info">
                        Partners
                      </li>
                      <%# <% current_user.accept_request.each do |user|%>
                        <%# <li class="list-group-item d-flex justify-content-between align-items-center"> %>
                          <%# <%= user.name %> 
                        <%# </li> %>
                      <%# <% end %> 
                    </ul>
                  </div>  
                </div>
              </div>
            </div>
          </div>
        </div>  
      </section>
    </div>
  </div>     

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Entrenamientos:</strong>
  <%= @user.trainings.join(', ') %>
</p>

<p>
  <strong>Image:</strong>
  <%= @user.image %>
</p>

<%= pie_chart @user_sport, legend: "bottom" %>
<%= line_chart @user_group, legend: ""%>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>