config/routes.rb
Rails.application.routes.draw do  
  resources :trainings
  
  resources :partners, only: [:new, :create, :destroy]
  
  resources :places do
    resources :trainings
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registration: 'user/registrations' }
  
  resources :users do
    collection do
       get 'dashboard'
    end 
    resources :trainings
  end

  root 'home#index'
end

app/views/shared/_carousel.html.erb
<div id="carousel" class="carousel slide custom-shadow" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://mountaingames.com/wp-content/uploads/2019/05/2018_Vail_Kyra_Mionske_feature-shot.jpg" class="d-center w-50" alt="">
    </div>
    
    <div class="carousel-item">
      <img src="https://www.vichealth.vic.gov.au/-/media/Images/VicHealth/sponsorshippolicy1200x525.jpg?h=525&la=en&w=1200&hash=AE8F82C0B994B33E79DF7584711D282B172AB497" class="d-center w-50" alt="">
    </div>

    <div class="carousel-item">
      <img src="https://www.salleurl.edu/sites/default/files/styles/capsalera_node/public/content/nodes/View%20Page/image/21433/39068/la-salle-sport-fitness-campus-barcelona.jpg" class="d-center w-50" alt="">    
    </div>

    <div class="carousel-item">
      <img src="https://areajugones.sport.es/wp-content/uploads/2020/06/skater-xl.jpg" class="d-center w-50" alt="">    
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_contact.html.erb
<!-- Contact -->
<section id="contact" class="custom-shadow p-5 m-5">
    <div class="row container mt-5">
        <div class="col-12 col-md-6 ">

            <div class="mb-3 mx-5">
                <form method="post" action="#">
                    <div class="fields">
                        <div class="field half">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" />
                        </div>
                        <div class="field half">
                            <label for="email">Email</label>
                            <input type="text" name="email" id="email" />
                        </div>
                        <div class="field">
                            <label for="message">Message</label>
                            <textarea name="message" id="message" rows="6"></textarea>
                        </div>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="Send Message" class="primary" /></li>
                        <li><input type="reset" value="Clear" /></li>
                    </ul>
                </form>                
            </div>
        </div>

        <div class="col-12 col-md-6 contacto">
            <div class="mb-5 mx-5"> 
                    <label class="mb-3 mt-2 pb-3"><i class="far fa-envelope"></i> Email: <a href="#"> informacion@partner.com</a></label>
                    <label class="my-3 py-5"><i class="fas fa-mobile-alt"></i> Teléfono: <a href="#"> +56 9 91234567</a></label>
                    <label class="my-3 py-3"><i class="fas fa-map-marked-alt"></i> Dirección: <a href="#"> Alguna Calle #5432, Santiago, Chile</a></label>
            </div>
        </div>
    </div>
</section>

app/views/shared/_follow.html.erb
<section class="social">
    <p class="mb-5">Síguenos</p>
        <div class="links">
            <a href="https://facebook.com">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="https://twitter.com">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="https://instagram.com">
                <i class="fab fa-instagram"></i>
            </a>
        </div>
</section>

app/views/shared/_footer.html.erb
<div class="footer-links mt-5 custom-shadow">
  <div class="row p-4">
    <div class="col-12 col-sm-4 pt-5 mt-5">
      <div>
        
          <h5 class="fw-bold">Acerca de</h5>
        
      </div>
      <div>Cómo funciona</div>
      <div>Creación</div>
      <div>Nosotros</div>
      <div>Qué queremos</div>
      <div>Startup</div>
      <div>Innovación</div>
    </div>
    
    <div class="col-12 col-sm-4 pt-5 mt-5">
      <div>
        
          <h5 class="fw-bold">Asistencia</h5> <%#Rol Administrador%>
        
      </div>
      <div>En qué te ayudamos</div>
      <div>Confianza y seguridad</div>
      <div>Denuncias</div>
      <div>Problemas con la app</div>
      <div>Contáctanos adm@example.com</div>
    </div>
    <div class="col-12 col-sm-4">
      <%= image_tag 'part.png' %>
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="footer">
  <div class="d-flex justify-content-center">
    <h6 class="fw-bolder">Nombre de app Copyright</h6><i class="far fa-copyright ms-1"></i>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg m-0 p-0">
  <div class="container">
    <div class="col-3 my-auto py-2" >
      <a href="#scrollspyHeading1" class="logo-btn" role="button">
        <%= image_tag "part.png", alt: "", width: "100", height: "80" %>
      </a>
    </div>

    <div class="col-5 my-auto p-2 radius-container custom-shadow">
      <div class="row px-2 align-content-center">
        <div class="col-11">
          <!--<input type="text" class="search-input">-->
            <%= form_tag(places_path, method: :get, class:"form-inline", role: 'search') do %>
              <div class="input-group">
                  <%= text_field_tag :location,
                  params[:location],
                  id: 'places_search',
                  class: 'form-control' %>              
                
                <div class="col-5 my-auto p-2">
                  <div class="input-group-btn search-panel px-0">
                    <%= button_to 'Clear', trainings_path, class: "btn btn-default" %>
                    <%= submit_tag 'Search', name: nil, class: "fas fa-search " %>
                  </div>
                  <%# <button class="search-btn">
                    <i class="fas fa-search"></i>
                  </button> %>
                </div>
              </div>
            <% end %>
        </div>
        
      </div>
    </div>

    

    <div class="col-1 my-auto">
      <div class="row justify-content-end">
        <div class="col-2 my-auto p-2">
          <a href="#" class="profile-btn d-flex justify-content-evenly" role="button" id="default">
            <!--<i>Notificaciones</i>-->
          </a>
        
        </div>
      </div>
    </div>

    <div class="col-3 my-auto">
      <div class="row justify-content-end">
        <div class="col-3 m-auto p-2 radius-container custom-shadow dropdown show">
          <a href="#" class="profile-btn d-flex justify-content-evenly" role="button" id="defaultDropdown" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
            <i class="fas fa-bars"></i><i class="far fa-user-circle"></i>
          </a>

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-lg-start mt-2 custom-shadow border-0" aria-labelledby="defaultDropdown">
            <% if user_signed_in? %>
                <li><a class="dropdown-item" href="#"><%= link_to 'Perfil', users_path%></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to 'Editar perfil', edit_user_registration_path %></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to 'Trainings', trainings_path %></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to 'Crear entrenamiento', new_training_path %></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to 'Buscar entrenamiento', places_path %></a></li>
                <li><a class="dropdown-item" href="#"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></a></li>                            
            <% else %>
              <li class="p-1"><a href="#"><%= link_to 'Regístrate', new_user_registration_path %></a></li>
              <li class="p-1"><a href="#"><%= link_to 'Iniciar sesión', new_user_session_path %></a></li>
              <li class="p-1"><a href="#"><%= link_to 'Administrador', new_admin_user_session_path %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navsecond.html.erb
<%# <div class="content">   
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Active</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
    </ul>
</div>  %>

<%#<nav class="navbar navbar-expand-lg navbar-light bg-light", style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><%= link_to 'Home', root_path %> <!--</a>-->
    <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Opciones
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <li><a class="dropdown-item" href="#"><%= link_to 'Editar perfil', edit_user_registration_path %></a></li>
              <li><a class="dropdown-item" href="#"><%= link_to 'Trainings', trainings_path %></a></li>
              <li><a class="dropdown-item" href="#"><%= link_to 'Crear entrenamiento', new_training_path %></a></li>
              <li><a class="dropdown-item" href="#"><%= link_to 'Buscar entrenamiento', trainings_path %></a></li> Generar el search para entrenamientos según tu ubicación-->
              <%#<li><a class="dropdown-item" href="#"><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %><!--</a></li>-->
              <!--<li><a class="dropdown-item" href="#"> link_to 'Administrador', new_admin_user_session_path </a></li>-->
            <%#<% else %>
              <!--<li><a class="dropdown-item" href="#"># link_to 'Administrador', new_admin_user_session_path </a></li>-->
              <%#<li><a class="dropdown-item" href="#"><%= link_to 'Regístrate', new_user_registration_path %><!--</a></li>
              <%#<li><a class="dropdown-item" href="#"><%= link_to 'Iniciar sesión', new_user_session_path %></a></li>-->
            <%#<% end %>
          <!--</ul>
        </li>
      </ul>-->
      


      <!--<form class="d-flex">
        <%#<%= search_form_for @q do |f| %>
          <%#<%= f.search_field :content_cont %>
          <%#<%= f.submit %>
        <%#<% end %>
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" >
      </form>-->
    <!--</div>
  </div>
</nav>-->




<%= form_with(model: place, local: false) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit data: { disable_with: 'Creando Lugar nuevo', confirm: 'Estás seguro?' } %>
  </div>
<% end %>





<div>
      <!--<script src="https://maps.googleapis.com/maps/api/js"></script>
      <script>
        //function initialize() {
         // var location = {lat: <%= @training.latitud %>. lng: <%= @training.longitude%>};
         // var map = new google.maps.Map(document.getElementById("map"), {
           // center: location,
           // zoom: 14,
          //}); %>

         // var marker = new google.maps.Marker({
          //  position: location,
         //   map: map
         // });

          // var infoWindow = new google.maps.InfoWindow({
          //   content: '<div id="content"><%= image_tag @training.cover_photo(:medium) %></div>'
          // });

          // infoWindow.open(map, marker);
        }

        google.maps.event.addDomListener(window, 'load', initialize);
      </script> -->



      <!--Clave API google MAPS AIzaSyDMpNrDZDtAqlja950Cee2DZtV_sa4I6KY-->

app/views/shared/_validation-messages.html.erb
<%# <% if object.errors.any? %>
    <%# <div id="error_explanation" class="alert alert-danger" role="alert"> %>
        <%# <p class="font-weight-bold"><%= pluralize(object.errors.count, "error") prohibited this <%= "#{object.class.name.downcase}" from being saved:</p> %> %> %>
        <%# <ul> %>
            <%# <% object.errors.full_messages.each do |msg| %> %>
                <%# <li><%= msg %></li> %>
            <%# <% end %> %>
        <%# </ul> %>
    <%# </div> %>
<%# <% end %> %> %>