config/routes.rb
Rails.application.routes.draw do  
  resources :trainings
  
  resources :partners, only: [:new, :create, :destroy]
  
  resources :places do
    resources :trainings
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registration: 'user/registrations' }
  
  resources :users do
    collection do
       get 'dashboard'
    end 
    resources :trainings
  end

  root 'home#index'
end

app/models/place.rb
class Place < ApplicationRecord
    #searchkick word_start: [:location]

    has_many :trainings

    scope :active, ->{ where(active: true) }
    
    # geocoded_by :location
    # after_validation :geocode, if: :location_changed?

    def to_s
        self.location    
    end

    def search_data
       {
            country: country,
            city: city,
            location: location, null: false          
       }
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  # GET /places or /places.json
  def index
    # @places = Place.all #.active scope
    @place = Place.new
    # Searchkick
    search = params[:location].present? ? params[:location] : nil
      @places = if search
        Place.where("country LIKE ? OR city LIKE? OR location LIKE?", "%#{search}%", "%#{search}%", "%#{search}%")
        #Place.search(search)
      else
        Place.all
      end
    end

  # GET /places/1 or /places/1.json
  def show
    # respond_to do |format|
    #   if @place.active
    #     format.html
    #     format.js
    #   else
    #     format.html { redirect_to root_path, notice: "Didn't find your place" }
    #   end
    # end
  end

  # GET /places/new
  def new
    @place = Place.new 
  end
  
  # GET /places/1/edit
  def edit
    # respond_to do |format|
    #   format.html { redirect_to @place }
    #   format.js
    # end
  end

  # POST /places or /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: "Place was successfully created." }
        format.js
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1 or /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: "Place was successfully updated." }
        format.js
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1 or /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def place_params
      params.require(:place).permit(:country, :city, :location, :latitude, :longitude, :active)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form-fields.html.erb
<div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: "form-control" %>
</div>
<div class="form-group">
    <%= f.label :location %>
    <%= f.text_field :location, class: "form-control" %>
</div>

<div class="actions">
    <%= f.submit class: "btn btn-success" %>

    <%# NOTE AUTHOR Only load the delete button when editing an author. Otherwise the delete button will appear on the new post view and raise an exception. %>
</div>


    <%# <% if params[:action] == 'edit' && params[:controller] == 'places' %>
        <%# <%= link_to "Delete #{@place.formatted_name}", place_path(@place), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    <%# <% end %> 

app/views/places/_form-with.html.erb
<%= form_with(model: place, class: 'places_form_with', url: "/trainings/create", method: :post, local: false) do |form| %>
  
  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %> <!-- data: { disable_with: 'Creando Lugar nuevo', confirm: 'Estás seguro?' } %>-->
  </div>
<% end %>

app/views/places/_form.html.erb
<%= form_with model: place, local: true, data: {
                                            controller: :maps,
                                            action: "google-maps-callback@window->maps#initializeMap"
                                            
                                            
                                            } do |form| %>
  

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :search %>
    <%= form.search_field :search, name: nil, class: 'form-control', data: { target: "maps.field", action: "keydown->maps#preventSubmit" } %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, class: "form-control", data: { target: "maps.latitude" }%>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, class: "form-control", data: { target: "maps.longitude" }%>
  </div>

  <%= content_tag :div, nil, data: { target: "maps.map" }, class: 'map' %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/places/_place.html.erb
<tr data-id="<%= place.id %>">
    <%= render 'place_detail', place: place %>
</tr>


<%#<li><%= place.location %><!--</li>-->

app/views/places/_place_detail.html.erb
<td><%=  place.country %></td>
<td><%=  place.city %></td>
<td><%=  place.location %></td>
<%# <td><%=  place.latitude %>
<%# <td><%=  place.longitude %>
<td><%= link_to 'Show', place, remote: true%></td>
<td><%= link_to 'Edit', edit_place_path(place), remote: true %></td>
<td><%= link_to 'Destroy', place, method: :delete, data: { remote: true, confirm: 'Are you sure?' } %></td>

app/views/places/create.js.erb
{ "content": "<%= j @place.title %>" }

app/views/places/destroy.js.erb
var tr = document.querySelector('tr[data-id="<%= @place.id %>"]')
tr.innerHTML = ''

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/edit.js.erb
var place_detail = document.querySelector('#place_detail')
place_detail.innerHTML = '<%= j render "form-with", place: @place %>'

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lugares</h1>

<table id="places">
  <thead>
    <tr>
      <th>País</th>
      <th>Ciudad</th>
      <th>Dirección</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

   <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.country %></td>
        <td><%= place.city %></td>
        <td><%= place.location %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

<%# <%= render 'form', place: @place %> 

  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.js.erb
$('<%= j render "form", title: "Nuevo Lugar" %>').modal();

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>País:</strong>
  <%= @place.country %>
</p>

<p>
  <strong>Ciudad:</strong>
  <%= @place.city %>
</p>

<p>
  <strong>Dirección:</strong>
  <%= @place.location %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @place.longitude %>
</p>

<p>
  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=400x300&center=#{@place.latitude},#{@place.longitude}&key=AIzaSyDKo32oRZX1c3LtHxc0hXodf24IXpFRtbo", alt: "Map" %> 
</p>

<p>
  <strong>Active:</strong>
  <%= @place.active %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>

app/views/places/show.js.erb
var place_detail = document.querySelector('#place_detail')

place_detail.innerHTML = '<p><strong>Country:</strong><%= @place.country %></p>'
place_detail.innerHTML += '<p><strong>City:</strong><%= @place.city %></p>'
place_detail.innerHTML += '<p><strong>Location:</strong><%= @place.location %></p>'

app/views/places/update.js.erb
var tr = document.querySelector('tr[data-id="<%= @place.id %>"]')
tr.innerHTML = '<%= j render "place_detail", place: @place %>'

var place_detail = document.querySelector('#place_detail')
place_detail.innerHTML = ''